[2:1-2:16]: ERROR: Definition for `x` already exists in scope.

